/*
 * DIO_config.h
 *
 *  Created on: May 14, 2019
 *      Author: Sherif Meimari
 */

#define DIO_PIN_0_DIRECTION OUT
#define DIO_PIN_1_DIRECTION OUT
#define DIO_PIN_2_DIRECTION OUT
#define DIO_PIN_3_DIRECTION OUT
#define DIO_PIN_4_DIRECTION OUT
#define DIO_PIN_5_DIRECTION OUT
#define DIO_PIN_6_DIRECTION OUT
#define DIO_PIN_7_DIRECTION OUT
#define DIO_PIN_8_DIRECTION OUT
#define DIO_PIN_9_DIRECTION OUT
#define DIO_PIN_10_DIRECTION OUT
#define DIO_PIN_11_DIRECTION OUT
#define DIO_PIN_12_DIRECTION OUT
#define DIO_PIN_13_DIRECTION OUT
#define DIO_PIN_14_DIRECTION OUT
#define DIO_PIN_15_DIRECTION OUT
#define DIO_PIN_16_DIRECTION OUT
#define DIO_PIN_17_DIRECTION OUT
#define DIO_PIN_18_DIRECTION OUT
#define DIO_PIN_19_DIRECTION OUT
#define DIO_PIN_20_DIRECTION OUT
#define DIO_PIN_21_DIRECTION OUT
#define DIO_PIN_22_DIRECTION OUT
#define DIO_PIN_23_DIRECTION OUT
#define DIO_PIN_24_DIRECTION IN
#define DIO_PIN_25_DIRECTION OUT
#define DIO_PIN_26_DIRECTION OUT
#define DIO_PIN_27_DIRECTION OUT
#define DIO_PIN_28_DIRECTION OUT
#define DIO_PIN_29_DIRECTION OUT
#define DIO_PIN_30_DIRECTION OUT
#define DIO_PIN_31_DIRECTION OUT