/*
 * SEVEN_SEGMENT_config.h
 *
 *  Created on: May 21, 2019
 *      Author: Sherif Meimari
 */

#define SEVEN_SEGMENT_0_MODE CATHODE
#define SEVEN_SEGMENT_1_MODE CATHODE

#define SEVEN_SEGMENT_EN_0_PIN DIO_PIN_18
#define SEVEN_SEGMENT__EN_1_PIN DIO_PIN_19

#define SEVEN_SEGMENT_A_PIN DIO_PIN_20
#define SEVEN_SEGMENT_B_PIN DIO_PIN_21
#define SEVEN_SEGMENT_C_PIN DIO_PIN_22
#define SEVEN_SEGMENT_D_PIN DIO_PIN_23

#define SEVEN_SEGMENT_DISP_PIN DIO_PIN_8 